stages:
  - deploy-dev
  - deploy-prod

deploy-prod:
  stage: deploy-prod
  script:
    - cd /var/www/onelinks.frontend
    - git pull
    - yarn
    - yarn run build
  only:
    - master
  tags:
    - deploy

deploy-dev:
  stage: deploy-dev
  script:
    - cd /var/www/dev.onelinks.frontend
    - git pull
    - yarn
    - yarn run build --mode development
  only:
    - dev
  tags:
    - deploy

