stages:
  - deploy


deploy:
  stage: deploy
  script:
    - cd /var/www/onelinks.frontend
    - git pull
    - docker-compose -f docker-compose.prod.yml up -d --build
  only:
    - master
  tags:
    - deploy


