version: '3'

services:
  nginx:
    container_name: onelinks_client_nginx
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./var/log/nginx:/var/log/nginx/
    ports:
      - '8082:80'


networks:
  default:
    external:
      name: onelinks_network
