export enum RouterNameEnum {
    AuthLogin = 'AuthLogin',
    Main = 'Main',
    Candidates = 'Candidates',
    Partners = 'Partners',
    MaterialPresentation = 'MaterialPresentation',
    MaterialDocuments = 'MaterialDocuments',
    MaterialInfoPacks = 'MaterialInfoPacks',
    Training = 'Training',
    LeaderCourses = 'LeaderCourses',
    Materials = 'Materials',
    Calendar = 'Calendar',
    Chat = 'Chat',
    Course = 'Course',
    Lesson = 'Lesson',
    TrainingMain = 'TrainingMain',
    TrainingCourses = 'TrainingCourses',
    TrainingClub = 'TrainingClub',
    TrainingLeaders = 'TrainingLeaders',
}
